// Code in this file is ADDON-ONLY (ha-ai-proxy container deployment).
// It is NOT generated by sync_vendor.sh — keep it hand-maintained.
//
// Why this file exists:
//   Upstream wild-work is a desktop daemon that logs in via a local 127.0.0.1
//   callback listener (login_trae.Start). A remote HA container has no such
//   local browser, so the addon needs:
//     - AuthURL:       build the Trae auth URL with a PUBLIC callback
//                      (http://<ha>:7863/api/trae-cb) instead of 127.0.0.1
//     - StartOn:       listen on a given addr (0.0.0.0 in container) but still
//                      point the auth URL at the public callback
//     - Complete:      parse the browser-captured callback URL and finish login
//     - CompleteRefresh: direct refreshToken exchange (most robust, no callback)
//
// These functions reuse the unexported helpers in login.go (randHex,
// randNumericID, newUUID, writeState, state, ParseCallback, Poll) so they stay
// in sync with upstream automatically.

package login_trae

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/rockswang/workbuddy-wild/internal/auth"
	"github.com/rockswang/workbuddy-wild/internal/traework"
)

// AuthURL 生成 Trae 授权 URL，回调指向公网 callbackBase（如 http://<ha>:7863/api/trae-cb）。
// 与桌面版 Start 不同：不依赖本机 127.0.0.1 监听，适配异地容器。
func AuthURL(statePath, callbackBase string) (string, error) {
	machineID := randHex(32)
	deviceID := randNumericID()
	codeVerifier, codeChallenge := traework.GenPKCE()
	st := state{MachineID: machineID, DeviceID: deviceID, CodeVerifier: codeVerifier}
	if err := writeState(statePath, st); err != nil {
		return "", err
	}
	// 注意：回调端点就是面板自身的 /api/trae-cb（见 login_ui.py _handle_trae_cb），
	// 不要附加 /authorize 后缀——否则授权页跳回 /api/trae-cb/authorize 会 404。
	callback := strings.TrimRight(callbackBase, "/")
	u, _ := url.Parse(traework.ConsoleHost + "/authorization")
	v := u.Query()
	v.Set("login_version", "1")
	v.Set("auth_from", "solo")
	v.Set("login_channel", "native_ide")
	v.Set("plugin_version", traework.PluginVersion)
	v.Set("auth_type", "local")
	v.Set("client_id", traework.ClientID)
	v.Set("redirect", "0") // 与已验证可工作的 trae2api-web/桌面版一致：授权页登录后跳转回 auth_callback_url
	v.Set("login_trace_id", newUUID())
	v.Set("auth_callback_url", callback)
	v.Set("machine_id", machineID)
	v.Set("device_id", deviceID)
	v.Set("x_device_id", deviceID)
	v.Set("x_machine_id", machineID)
	v.Set("x_device_brand", traework.DeviceBrand)
	v.Set("x_device_type", "windows")
	v.Set("x_os_version", traework.OSVersion)
	v.Set("x_env", "")
	v.Set("x_app_version", traework.IdeVersion)
	v.Set("x_app_type", "stable")
	v.Set("code_challenge", codeChallenge)
	v.Set("code_challenge_method", "S256")
	v.Set("hide_saas_login", "true")
	v.Set("channel_name", "common")
	v.Set("click_id", "TRAE SOLOSetup-stable-"+traework.PluginVersion)
	u.RawQuery = v.Encode()
	return u.String(), nil
}

// StartOn 启动一次性回调监听（容器内可监听 0.0.0.0）并返回授权 URL。
// 与 AuthURL 配合：auth URL 的回调指向公网 callbackBase，而非本机监听地址。
func StartOn(client *http.Client, statePath, listenAddr, callbackBase string) (string, error) {
	machineID := randHex(32)
	deviceID := randNumericID()
	_, codeVerifier := traework.GenPKCE()
	ln, err := net.Listen("tcp", listenAddr)
	if err != nil {
		return "", err
	}
	st := state{MachineID: machineID, DeviceID: deviceID, CodeVerifier: codeVerifier}
	if err := writeState(statePath, st); err != nil {
		_ = ln.Close()
		return "", err
	}
	srv := &http.Server{ReadHeaderTimeout: 15 * time.Second}
	srv.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			if body, _ := io.ReadAll(io.LimitReader(r.Body, 64<<10)); len(body) > 0 {
				var m map[string]any
				if err := json.Unmarshal(body, &m); err == nil {
					q := r.URL.Query()
					for k, val := range m {
						if s, ok := val.(string); ok && q.Get(k) == "" {
							q.Set(k, s)
						}
					}
					r.URL.RawQuery = q.Encode()
				}
			}
		}
		q := r.URL.Query()
		st.Host = q.Get("host")
		if st.Host == "" {
			st.Host = traework.OAuthHost
		}
		info := ParseCallback(r.URL.String())
		st.RefreshToken = info.RefreshToken
		st.AccessToken = info.AccessToken
		st.AuthCode = info.AuthCode
		if st.RefreshToken == "" && st.AccessToken == "" && st.AuthCode == "" {
			st.Err = "missing refreshToken in callback"
		}
		_ = writeState(statePath, st)
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte("<html><body style='font-family:sans-serif;padding:24px'>TraeWork 登录已完成，可以关闭此页面。</body></html>"))
		go func() {
			ctx, cancel := context.WithTimeout(context.Background(), time.Second)
			defer cancel()
			_ = srv.Shutdown(ctx)
		}()
	})
	go func() { _ = srv.Serve(ln) }()
	go func() {
		time.Sleep(5 * time.Minute)
		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
		defer cancel()
		_ = srv.Shutdown(ctx)
	}()
	u, err := AuthURL(statePath, callbackBase)
	if err != nil {
		_ = ln.Close()
		return "", err
	}
	return u, nil
}

// Complete 解析浏览器回调 URL 并完成换 token + 账号信息（委托 Poll）。
func Complete(client *http.Client, statePath, callbackRawURL string) (Result, error) {
	var st state
	raw, err := os.ReadFile(statePath)
	if err != nil {
		return Result{}, err
	}
	if err := json.Unmarshal(raw, &st); err != nil {
		return Result{}, err
	}
	if st.Err != "" {
		return Result{}, errors.New(st.Err)
	}
	if u, err := url.Parse(callbackRawURL); err == nil {
		if h := u.Query().Get("host"); h != "" {
			st.Host = h
		}
	}
	info := ParseCallback(callbackRawURL)
	st.RefreshToken = info.RefreshToken
	st.AccessToken = info.AccessToken
	st.AuthCode = info.AuthCode
	if st.RefreshToken == "" && st.AccessToken == "" && st.AuthCode == "" {
		return Result{}, ErrPending
	}
	if err := writeState(statePath, st); err != nil {
		return Result{}, err
	}
	return Poll(client, statePath)
}

// CompleteRefresh 直接用 refreshToken 换 token（最稳，不依赖浏览器回调/127.0.0.1 监听）。
func CompleteRefresh(client *http.Client, refreshToken, host string) (Result, error) {
	refreshToken = strings.TrimSpace(refreshToken)
	if refreshToken == "" {
		return Result{}, errors.New("empty refreshToken")
	}
	if host == "" {
		host = traework.OAuthHost
	}
	c := traework.New()
	c.HTTP = client
	a := &auth.Auth{Kind: "traework", RefreshToken: refreshToken, ApiHost: host, Domain: "trae.cn"}
	if err := c.RefreshToken(a); err != nil {
		return Result{}, err
	}
	uid, nick, ent, err := c.GetUserInfo(a)
	if err != nil {
		return Result{}, err
	}
	return Result{AccessToken: a.AccessToken, RefreshToken: a.RefreshToken, ExpiresAt: a.ExpiresAt, Domain: "trae.cn", ApiHost: host, MachineID: a.MachineID, DeviceID: a.DeviceID, UID: uid, EnterpriseID: ent, Nickname: nick}, nil
}
